#!/usr/bin/env bash

wait-for-internet -q --timeout "${WFI_TIMEOUT:-10}" || exit 0

evry 4 weeks -chief-animelist && {
	cd "$REPOS/dbsentinel/data" || exit 1
	printlog 'chief-animelist: updating MasterDChief anime list for donghua/aeni tags'
	MALEXPORT_DIR='./malexport' malexport update lists -o anime -u MasterDChief
	printlog 'chief-animelist: pushing MasterDChief anime list to vultr'
	rsync -Pavhz ./malexport vultr:./code/dbsentinel/data
}
