#!/bin/bash
# run from my computer to approve guest book comments at https://sean.fish/#
# specify one of --approve-comments, --review-comments, --print-count or --print-new-comments to this script
# defaults to --approve-comments
# see https://github.com/seanbreckenridge/glue/blob/master/production_server

declare FLAG COMMAND
FLAG="${1:---approve-comments}"
[[ "$FLAG" == "--approve-comments" ]] && rm -f "$(evry location -guestbook_comments)"
# shellcheck disable=SC2016
COMMAND="$(printf 'cd ~/code/glue/ && PATH="${HOME}/.asdf/shims/:$PATH" ./production_server "%s"' "${FLAG}")"
printf "Running: '%s'\n" "${COMMAND}" 1>&2
exec ssh vultr "${COMMAND}"
