#!/bin/sh

# location of application directories
export CODE="${HOME}/code"
export VENVS="${HOME}/.local/share/virtualenvs"
export MID_CACHE="${HOME}/.mal-id-cache"
export MID_CACHE_REPO="${MID_CACHE}/repo"
export NOTIFY_BOT="${CODE}/mal-notify-bot"
export COUNTDOWN_BOT="${CODE}/discord-countdown-bot"
export UNAP_SERVER="${CODE}/mal-unapproved"
export DOCKER_JIKAN="${CODE}/docker-jikan"
export WCA_USERINFO="${CODE}/wca_userinfo"
export ALBUMS="${CODE}/albums"

export LOGS_BASE="${HOME}/logs"
export MID_LOGS="${LOGS_BASE}/mal-id-cache"
export NOTIFY_LOGS="${LOGS_BASE}/mal-notify-bot"
export COUNTDOWN_LOGS="${LOGS_BASE}/discord-countdown-bot"
export UNAP_LOGS="${LOGS_BASE}/mal-unapproved"
export DOCKER_LOGS="${LOGS_BASE}/docker-jikan"
export WCA_LOGS="${LOGS_BASE}/wca_userinfo"
export ALBUMS_LOGS="${LOGS_BASE}/albums"

export SUPERVISOR_LOGS="${LOGS_BASE}/supervisor"
