#!/bin/sh

# location of application directories
CODE="${HOME}/code"
VENVS="${HOME}"/.local/share/virtualenvs
MID_CACHE="${HOME}/.mal-id-cache"
MID_CACHE_REPO="${MID_CACHE}/repo"
NOTIFY_BOT="${CODE}/mal-notify-bot"
COUNTDOWN_BOT="${CODE}/discord-countdown-bot"
UNAP_SERVER="${CODE}/mal-unapproved"
DOCKER_JIKAN="${CODE}/docker-jikan"
FOREVER_WEB="${CODE}/forever-webui"

MID_LOGS="${HOME}/logs/mal-id-cache"
NOTIFY_LOGS="${HOME}/logs/mal-notify-bot"
COUNTDOWN_LOGS="${HOME}/logs/discord-countdown-bot"
UNAP_LOGS="${HOME}/logs/mal-unapproved"
DOCKER_LOGS="${HOME}/logs/docker-jikan"
FOREVER_LOGS="${HOME}/logs/forever-web"

