#!/bin/bash

# location of application directories
declare -rx CODE="${HOME}/code"
declare -rx VENVS="${HOME}/.local/share/virtualenvs"
declare -rx MID_CACHE="${HOME}/.mal-id-cache"
declare -rx MID_CACHE_REPO="${MID_CACHE}/repo"
declare -rx NOTIFY_BOT="${CODE}/mal-notify-bot"
declare -rx COUNTDOWN_BOT="${CODE}/discord-countdown-bot"
declare -rx DOCKER_JIKAN="${CODE}/jikan-docker"
declare -rx WCA_USERINFO="${CODE}/wca_userinfo"
declare -rx ALBUMS="${CODE}/albums"
declare -rx GLUE="${CODE}/glue"
declare -rx TODO_NOTIFY="${CODE}/todotxt_deadline_notify"
declare -rx MNU_GSHEETS="${CODE}/mnu_gsheets"
declare -rx CHECKER_MAL="${CODE}/checker_mal"
declare -rx PROJECTS="${CODE}/projects"

declare -rx SHORTURL_DATA="${HOME}/shorturls"

declare -rx LOGS_BASE="${HOME}/logs"
declare -rx MID_LOGS="${LOGS_BASE}/mal-id-cache"
declare -rx NOTIFY_LOGS="${LOGS_BASE}/mal-notify-bot"
declare -rx COUNTDOWN_LOGS="${LOGS_BASE}/discord-countdown-bot"
declare -rx DOCKER_LOGS="${LOGS_BASE}/jikan-docker"
declare -rx WCA_LOGS="${LOGS_BASE}/wca_userinfo"
declare -rx ALBUMS_LOGS="${LOGS_BASE}/albums"
declare -rx GLUE_LOGS="${LOGS_BASE}/glue"
declare -rx TODO_NOTIFY_LOGS="${LOGS_BASE}/todotxt_deadline_notify"
declare -rx CHECKER_MAL_LOGS="${LOGS_BASE}/checker_mal"
declare -rx PROJECTS_LOGS="${LOGS_BASE}/projects"

declare -rx SUPERVISOR_LOGS="${LOGS_BASE}/supervisor"
