#!/bin/bash

# function to check if required commands exist prior to bootstrap
require() {
	if [[ ! $(command -v "$1") ]]; then
		printf "requires '%s', Install that and re-run\n" "$1"
		exit 1
	fi
}

# $1: url, $2: location
reclone_dir() {
	[ -d "$2" ] && rm -rf "$2"
	git clone --depth=1 --branch=master "$1" "$2"
	rm -rf "$2/.git"
}

# removes any files currently in the REMOVE_FILES array
remove_files() {
	for remove_file in "${REMOVE_FILES[@]}"; do
		rm -vrf "$remove_file"
	done
}

# $1: static site folder to move to document root root
move_to_document_root() {
	TARGET="${DOCUMENT_ROOT}/$(basename "$1")"
	if [ -d "$DOCUMENT_ROOT" ]; then
		sudo rm -rf "$TARGET"
		sudo mv -v "$1" "$DOCUMENT_ROOT"
	else
		printf "Error moving files: '%s' does not exist.\n" "$DOCUMENT_ROOT"
	fi
}

require git
require elm
require make
require python3
require realpath

CUR_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
BUILD_DIR="${CUR_DIR}/static_build"

DOCUMENT_ROOT="/var/www/html"

# specifies URI path
DVD_DIR="${BUILD_DIR}/dvd"
XKCD_DIR="${BUILD_DIR}/xkcd"

# clone dirs
reclone_dir "https://github.com/seanbreckenridge/xqc-dvd" "$DVD_DIR"
reclone_dir "https://github.com/seanbreckenridge/xkcd-favorites" "$XKCD_DIR"

## Build each Site

## DVD DIR ################

cd "$DVD_DIR"
make

REMOVE_FILES=(".gitignore" ".github" "elm-stuff" "elm.json" "LICENSE" "Makefile" "README.md" "src")
remove_files

move_to_document_root "$DVD_DIR"

## XKCD DIR ###############

cd "$XKCD_DIR"
python3 -m pip install --user -r requirements.txt
python3 generate.py

REMOVE_FILES=("favorites.yaml" "generate.py" "LICENSE" "README.md" "requirements.txt" ".nojekyll" ".gitignore")
remove_files

move_to_document_root "$XKCD_DIR"

rm -rf "$BUILD_DIR"
