#!/bin/bash
# uses goaccess to summarize nginx logs

cd /var/log/nginx

MY_IP="$(pinky -fbw | awk 'NR < 2 {print $5}')"
FILTER_STR="/netdata|/logs|^::1|^127.0.0.1|^${MY_IP}"

case "$1" in
status)
	[ -z "$2" ] && echo "specify HTTP status as second argument" && exit 1
	awk -v field=$2 '$9 == field {print}' access.log
	;;
raw)
	# just print the logs
	cat access.log
	;;
filtered)
  # print all logs, without my IP/netdata/logs
	cat access.log | grep -iv -E "$FILTER_STR"
  ;;
all)
	# goaccess terminal all logs
	tail -f -n +1 access.log | grep -iv -E "$FILTER_STR" | goaccess --log-format=COMBINED -
	;;
*)
	echo "Must specify 'all', 'raw', 'filtered' or 'status' as argument"
	exit 1
	;;
esac
