#!/bin/bash
# uses goaccess to summarize nginx logs

cd /var/log/nginx
case "$1" in
  recent)
    tail -f -n +1 access.log | goaccess --log-format=COMBINED -
    ;;
  all)
   { zcat access.log.*.gz && tail -f -n +1 access.log; } | goaccess --log-format=COMBINED -
     ;;
  html)
   { zcat access.log.*.gz && cat access.log; } | goaccess --log-format=COMBINED -o "${HOME}/.goaccess.html" -
     ;;
  *)
    echo "Must specify 'recent', 'all', or 'html' as argument"
    exit 1
esac
