#!/usr/bin/env bash
# Print logs for all processes running
# in order to view nginx logs without sudo, add yourself to adm:
# sudo usermod -a -G adm $(whoami)

cd "${HOME}/logs" || exit 1
#find /var/log/nginx /var/log/fail2ban.log . -type f -name "*.log"
find /var/log/nginx /var/log/fail2ban.log . -type f -name "*.log" | xargs -r tail -n 50 -f

