#!/bin/bash
# Youtube-DLs a URL up to the BASE_URL directory
# and copies a link to the your clipboard
# Any additional args are passed to youtube-dl
# Nginx Block:
# location /m/ {
#   alias /home/sean/.ytdl/;  # location
#
#   # dont serve directories
#   try_files $uri =404;
#   autoindex off;
# }

########## CONFIGURATION

# server information
readonly SYNC_USER="sean"
readonly SYNC_KEYFILE="${HOME}/.ssh/vultr" # ssh keyfile
readonly TO_SERVER=140.82.50.43
readonly BASE_URL="https://sean.fish/m"

######### SETUP

# use a wordlist to generate a readable link
readonly WORDLIST="${HOME}/.local/share/wordlist.txt"
[[ ! -r "${WORDLIST}" ]] && curl --silent "https://gist.githubusercontent.com/seanbreckenridge/603242562a59264f6afe8a3056bf6932/raw/98d35708fa344717d8eee15d11987de6c8e26d7d/1-1000.txt" >"$WORDLIST"

# (999 * 998) possible URLs
random_readable_url() {
	printf '%s\n' "$(shuf -n2 "$WORDLIST" | awk '{ printf "%s%s", toupper(substr($1, 1, 1)), substr($1, 2) }')"
}

# generate a unique URL to host this on
# do a HEAD request to check if the URL 404s before returning
generate_non_existent_url() {
	local key URL
	while true; do
		key="$(random_readable_url)" # e.g. 'WordsFrom'
		URL="${BASE_URL}/${key}"
		if curl --output /dev/null --silent --head --fail "${URL}"; then
			: # the URL exists, retry
		else
			printf '%s' "$key"
			break
		fi
	done
}

# parse arguments
declare filename extension
extension='mp4'
[[ -z "$1" ]] && {
	printf "[mediaproxy] Error: Must provide a URL to mirror\n" >&2
	exit 1
}
# check if user asked to convert to audio
for arg in "$@"; do
	if [[ "$arg" == "-x" || "$arg" == "--extract-audio" ]]; then
		extension='mp3'
	fi
done
# generate random name
filename="$(generate_non_existent_url)"
readonly extension filename

########## RUN

# validate arguments
echo "[mediaproxy] Running command locally to ensure it works..."
if cd /tmp; then
	youtube-dl "--skip-download" "$@" || exit $?
else
	echo "somehow /tmp doesn't exist" >&2
	exit 1
fi

# run youtube-dl on server
# ffmpeg it to the correct location/extension
declare ytdl_cmd
ytdl_cmd="python3 -m youtube_dl $*"
echo "[mediaproxy] Running command on server: ${ytdl_cmd}"

set -e
ssh -i "$SYNC_KEYFILE" "${SYNC_USER}@${TO_SERVER}" "$(printf '
mkdir -p "${HOME}/.ytdl"
find "${HOME}/.ytdl" -type f -mtime +31 -delete
TMPDIR="$(mktemp -d /tmp/ytdl.XXXXX)"
cd "${TMPDIR}"
eval "%s" && {
  downloaded_file="$(find . -type f -mindepth 1 | head -n1)"
  ffmpeg -i "${downloaded_file}" "${HOME}/.ytdl/%s"
  rm "${downloaded_file}"
}
' "${ytdl_cmd}" "${filename}.${extension}")" | tee -a /tmp/mediaproxy.log
set +e

readonly PUBLIC_URL="${BASE_URL}/${filename}.${extension}"
printf '[mediaproxy] %s\n' "$PUBLIC_URL"
printf '%s' "$PUBLIC_URL" | clipcopy
# https://sean.fish/d/notify
notify "mediaproxy" "Copied mirror link to clipboard."
