#!/bin/bash -exu
# updates the mnu spreadsheet
# https://github.com/seanbreckenridge/mnu_gsheets

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "$THIS_DIR"

source ./directories

cd "$MNU_GSHEETS"
git pull
python3 -m pipenv install
python3 -m pipenv run ./update
