#!/bin/bash
# shorten <url> [path]
# uses my URL shortener (https://gitlab.com/seanbreckenridge/no-db-static-shorturl)
# to shorten a URL to some random string
# if 'path' (second argument) isn't provided,
# the server generates a random hash
# e.g.
# shorten "https://wiki.archlinux.org/index.php/File_opener" open
# would return "https://sean.fish/s/open"
# which now redirects to the archwiki link

# handle user input
readonly UPLOAD_TO="https://sean.fish/s/"
readonly SHORTURL_TOKEN="${SHORTURL_TOKEN:?No shorturl token set}"
readonly URL="${1:?No url provided to shorten}"
readonly HASH="$2" # fine if this is empty

# create JSON string
declare data
data="$(printf '{"key":"%s", "url":"%s","hash":"%s"}' "$SHORTURL_TOKEN" "$URL" "$HASH")"

# make request to server
declare SHORTURL_PART
SHORTURL_PART="$(curl --silent "Content-Type: application/json" --request POST --data "$data" "$UPLOAD_TO")"

# check for 'error' in response text
if grep -qi error <<<"$SHORTURL_PART"; then
	echo "${SHORTURL_PART}"
else
	echo "${UPLOAD_TO}${SHORTURL_PART}"
	# copy the url to my clipboard
	echo -n "${UPLOAD_TO}${SHORTURL_PART}" | clipcopy
fi
