#!/bin/bash
# A wrapper script for supervisord/supervisorctl
# which sources my environment variables
#
# This supports completion, run
# complete -F _longopt super in ~/.bash_profile
# to generate autocompletion for bash

# source application environment variables
CUR_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
source "${CUR_DIR}/directories"
export VPS_DIR="$CUR_DIR"
# load password
SUPERVISOR_PW="$(jq -jr '.supervisor_password' "${CUR_DIR}/secret")"
SHORTURL_KEY="$(jq -jr '.shorturl_token' "${CUR_DIR}/secret")"
CHECKER_MAL_SECRET="$(jq -jr '.checker_mal_secret' "${CUR_DIR}/secret")"
CHECKER_MAL_URI="$(jq -jr '.checker_mal_uri' "${CUR_DIR}/secret")"
MAL_CLIENTID="$(jq -jr '.mal_clientid' "${CUR_DIR}/secret")"
BACK_ARROW=1
export SHORTURL_KEY SUPERVISOR_PW CHECKER_MAL_SECRET CHECKER_MAL_URI BACK_ARROW MAL_CLIENTID

# add asdf global versions to $PATH
export PATH="${HOME}/.asdf/shims/:$PATH"

function run_super() {
	case "$1" in
	--kill)
		if pgrep -x supervisord >/dev/null 2>&1; then
			run_super --ctl "stop all"
			tail "$SUPERVISOR_LOGS"/*.log
			pkill -x supervisord
		else
			echo "No supervisord process running..." 1>&2
			return 1
		fi
		;;
	--daemon)
		supervisord --configuration="${CUR_DIR}/supervisord.conf"
		;;
	--foreground)
		# run supervisor
		supervisord --configuration="${CUR_DIR}/supervisord.conf" -n
		;;
	--ctl)
		shift # remove 'ctl' from arg list
		supervisorctl --configuration="${CUR_DIR}/supervisord.conf" "$@"
		;;
	-h | --help | *)
		# parse this case statement to get the choices
		# shellcheck disable=SC2021
		SPECIFY_CHOIES="$(grep -P '^\s*--\w+\)\s*$' "${HOME}/vps/super" | tr -d '[ )\t]')"
		printf "Must specify one of:\n%s\n" "$SPECIFY_CHOIES" 1>&2
		return 1
		;;
	esac
}

run_super "$@" || exit $?
