#!/usr/bin/env bash

# Keeps the last 10000 lines of logs for each logfile in ~/logs
# Uses sponge to make sure logs being written when
# the file is being modified aren't lost
#
# Note: seems to break something about how
# forever is connected to the file
# probably a good idea to run:
# truncate_logs && restart
# and only run this periodically

KEEP_LINES=10000

while IFS= read -r -d '' file; do
	tail -n $KEEP_LINES "$file" | sponge "$file"
	wc -l "$file"
done < <(find "${HOME}/logs" -type f -print0)
