#!/bin/bash
# Filters out netdata/log/my requests from the
# goaccess html output

MY_IP="$(pinky -fbw | awk 'NR < 2 {print $5}')"
FILTER_STR="/netdata|/logs|^::1|^127.0.0.1|^${MY_IP}"
OUTPUT_FILE="${HOME}/.goaccess_html/index.html"
NGINX_LOGFILE=/var/log/nginx/access.log

while true; do
	grep -ivE "$FILTER_STR" "$NGINX_LOGFILE" | goaccess --log-format=COMBINED -o "$OUTPUT_FILE" -
	sleep 600
done
